#!/bin/sh
set -eu

CLIENT_ID="${1:-}"

case "$CLIENT_ID" in
    BM-[0-9][0-9][0-9][0-9][0-9][0-9]) ;;
    *) echo "Invalid client id" >&2; exit 1 ;;
esac

ROOT=/var/lib/backupmanager-provider
TARGET="$ROOT/$CLIENT_ID"

install -d -o backupstore -g backupstore -m 2770 "$TARGET"
install -d -o backupstore -g backupstore -m 2770 "$TARGET/data"
install -d -o backupstore -g backupstore -m 2770 "$TARGET/database"
install -d -o backupstore -g backupstore -m 2770 "$TARGET/config"

chown backupstore:backupstore \
    "$TARGET" \
    "$TARGET/data" \
    "$TARGET/database"

chmod 2770 \
    "$TARGET" \
    "$TARGET/data" \
    "$TARGET/database"
