#!/usr/bin/python3 -I
import sys
sys.path.insert(0, '/usr/local/lib/backupmanager')
from backupmanager.config import load
from backupmanager.control import save
if len(sys.argv) != 3:
    raise SystemExit('Usage: backupmanager-schedule DAYS HH:MM')
save(load(), {'days': sys.argv[1], 'time': sys.argv[2]})
